# Chapter 2. Getting Started with NumPy
+ Introduction to the NumPy Ndarrays
+ Ndarray properties
+ NumPy constants

## NumPy and Ndarrays
+ NumPy is the fundamental package for numerical computation
+ Ndarray - is a multidimensional array (also known as a container) of items that have the same datatype and size

Особенности Ndarray:
+ размер и тип данных опредлеяем при создании
+ доступ к элементам через индекс
+ ндекс начинается с 0


In [2]:
import numpy as np

l1 =[1,2,3]
x = np.array(l1, dtype=np.int16)
x

array([1, 2, 3], dtype=int16)

In [4]:
y = np.array([3, 4, 5], dtype=np.int16)
y

array([3, 4, 5], dtype=int16)

In [5]:
print(y)
print(type(y))

[3 4 5]
<class 'numpy.ndarray'>


## Indexing in Ndarrays

In [6]:
print(x[0]), print(x[-1])

1
3


(None, None)

## Indexing in Ndarrays of More Than One Dimension

In [7]:
x1 = np.array([[1, 2, 3], 
              [4, 5, 6]], 
             np.int16)
x1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [9]:
x1[0,0], x1[-1,-1]

(1, 6)

In [11]:
x1[0,:]

array([1, 2, 3], dtype=int16)

In [12]:
x1[:,1]

array([2, 5], dtype=int16)

In [13]:
x1 * 10

array([[10, 20, 30],
       [40, 50, 60]], dtype=int16)

## Ndarray Properties

In [18]:
x2 = np.array([[[1,2,3],
               [4,5,6]],
              [[0,-1,-2],
               [-3,-4,-5]]],
             np.int16)
x2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 0, -1, -2],
        [-3, -4, -5]]], dtype=int16)

In [19]:
# number of dimensions
x2.ndim

3

In [20]:
# shape of the Ndarray
x2.shape

(2, 2, 3)

In [21]:
# datatype of the members
x2.dtype

dtype('int16')

In [23]:
# umber of bytes required in the memory
x2.nbytes

24

In [25]:
# transpose
x2.T

array([[[ 1,  0],
        [ 4, -3]],

       [[ 2, -1],
        [ 5, -4]],

       [[ 3, -2],
        [ 6, -5]]], dtype=int16)

## NumPy Constants

In [26]:
np.inf

inf

In [27]:
np.NAN

nan

In [28]:
np.NINF

-inf

In [29]:
np.NZERO

-0.0

In [31]:
np.PZERO

0.0

In [32]:
np.e

2.718281828459045

In [33]:
np.euler_gamma

0.5772156649015329

In [34]:
np.pi

3.141592653589793

## Slicing Ndarrays

In [35]:
a1 = np.array([1,2,3,4,5,6,7])
a1

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
a1[2:4]

array([3, 4])

In [37]:
a1[3:]

array([4, 5, 6, 7])

In [39]:
a1[:3]

array([1, 2, 3])

In [40]:
a1[-4:-1]

array([4, 5, 6])

In [41]:
a1[1:6:2]

array([2, 4, 6])